export const routes = {
    home: "/",
    about: "ve-chung-toi",
    login: "dang-nhap",
    register: "dang-ky",
    forget: "quen-mat-khau",
    resetpassword: "da-doi-mat-khau",
    blog: "blog",
    services: "dich-vu",
    updateprofile: "cap-nhat-thong-tin",
    product: "san-pham",
    skinconsultation: "tu-van-cham-soc-da",
    bookingtherapist: "chon-chuyen-vien", 
    calendar: "lich-hen",
    additionalproducts: "san-pham-bo-sung",
    skincarebooking: "dat-lich",
    checkout: "xac-nhan-thong-tin",

    confirmbooking: "xac-nhan-dat-lich",
    staffmanagement: "quan-ly-nhan-vien",
}
