export const routes = {
    home: "/",
    about: "ve-chung-toi",
    login: "dang-nhap",
    register: "dang-ky",
    forgot: "quen-mat-khau",
    resetpassword: "da-doi-mat-khau",
    blog: "blog",
    services: "dich-vu",
    updateprofile: "cap-nhat-thong-tin",
    product: "san-pham",
    skinconsultation: "tu-van-cham-soc-da",
    calendar: "lich-hen",
    confirmbooking: "xac-nhan-dat-lich",
    staffmanagement: "quan-ly-nhan-vien",
}
